version: '3.5'

services:
  campaign_share_mysql:
    image: mysql:8.0
    container_name: campaign_share_mysql
    volumes:
      - campaign_share_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ChampaignShareDB
    networks:
      - campaign_share_local
    ports:
      - 3306:3306

volumes:
  campaign_share_db_data:
    name: campaign_share_db_data
    driver: local

networks:
  campaign_share_local:
    name: campaign_share_local
    driver: bridge
